name: DisplayKeys-IS Custom


# Trigger Build on:
on:
  push:
    branches: [ "main", "Development" ]
  pull_request:
    branches: [ "main" ]
    
# 
permissions:
  contents: read
  
#
jobs:    
  
  build_exe:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/venv/requirements.txt
        
      - name: Create EXE file
        run: | 
          # Command parameters for creating the .EXE file
          pyinstaller --onefile --noconsole --name "DisplayKeys-IS" --debug all ${{ github.workspace }}/venv/DisplayKeys-IS.py
          ls -l ${{ github.workspace }}/venv/dist/
  
  create_artifact:
    needs: build_exe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Make Artifact
        run: |
          # Replace the line with the appropriate command to copy or move the .EXE file
          cp ${{ github.workspace }}/venv/dist/DisplayKeys-IS.exe ${{ github.workspace }}/venv/DisplayKeys-IS.exe

        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DisplayKeys-IS
          path: ${{ github.workspace }}/DisplayKeys-IS.exe
#
