####################################################################################################################
# This Action exists solely for development and testing changes.
# If you want to create a release build, use the "DisplayKeys-IS Release" action instead.
#
# It is still automated to create a build when changes are merged to 'main' however, in order to ensure
# that any such changes are indeed working.
####################################################################################################################

name: DisplayKeys-IS Main


# Trigger Build on:
on:
  push:
    branches: [ "Development" ]
    paths-ignore:
      - "../README.md"
      - "./workflows/main.yml"
      - "./workflows/release.yml"
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# Actions project permission
permissions: write-all

#Individual Tasks to fullfill, to create artifact
jobs:    
  
  py_to_exe:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/ProjectFiles/config/requirements.txt
        
      - name: Create EXE file
        run: | 
          # Command parameters for creating the .EXE file
          pyinstaller ${{ github.workspace }}/ProjectFiles/DisplayKeys-IS.py --onefile --noconsole --name "DisplayKeys-IS" --debug all --distpath ${{ github.workspace }}/ProjectFiles/dist/ --add-data "${{ github.workspace }}/ProjectFiles/assets/DisplayKeys-IS.ico;." --icon ${{ github.workspace }}/ProjectFiles/assets/DisplayKeys-IS.ico --version-file ${{ github.workspace }}/ProjectFiles/config/version.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: DisplayKeys-IS
          path: ${{ github.workspace }}/ProjectFiles/dist/DisplayKeys-IS.exe
