name: DisplayKeys-IS Main


# Trigger Build on:
on:
  push:
    branches: [ "main", "Development" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# Actions project permission
permissions: read-all|write-all

#Individual Tasks to fullfill to create artifact
jobs:    
  
  build_exe:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/venv/requirements.txt
        
      - name: Create EXE file
        run: | 
          # Command parameters for creating the .EXE file
          pyinstaller --onefile --noconsole --name "DisplayKeys-IS" --debug all --distpath ${{ github.workspace }}/venv/dist/  ${{ github.workspace }}/venv/DisplayKeys-IS.py
      
  
  create_artifact:
    needs: build_exe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get Artifact
        run: |
          #list all in directory, sanity check that .exe was created 
          ls -a ${{ github.workspace }}/venv/dist/
          # Replace the line with the appropriate command to copy or move the .EXE file
          #cp ${{ github.workspace }}/venv/dist/DisplayKeys-IS.exe ${{ github.workspace }}/DisplayKeys-IS.exe
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DisplayKeys-IS
          path: ${{ github.workspace }}/venv/dist/DisplayKeys-IS.exe
