# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
##### Look into useing https://github.com/marketplace/actions/pyinstaller-action instead #####

name: DisplayKeys-IS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  pyinstaller-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1.2.0
        with:
          python_ver: '3.11'
          spec: 'src/venv/DisplayKey-IS.py' #Either .spec file or .py file location
          exe_path: '-' #Save location of exe
          #requirements: 'src/requirements.txt' #Dependencies to install
          upload_exe_with_name: 'DisplayKeys-IS' #Uploads the exe as an artifact
          options: --onefile, --name "DisplayKeys-IS", --windowed, --noconsole, #Options for PyInstaller command
