name: DisplayKeys-IS Release

# Trigger Build on:
on:
  # Manually create release and add artifact after release published
  workflow_dispatch:
  
# Actions project permission
permissions: write-all

jobs:

  publish_release:
    runs-on: windows-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
    
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "Testing" 
          tag_name: "test"
          body_path: ${{ github.workspace }}/ProjectFiles/config/releaselog.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
        ############## Add Artifact ############## 
        
      - name: get artifact
        uses: actions/download-artifact@v2
        with:
          name: DisplayKeys-IS
          path: ${{ github.workspace }}/ProjectFiles/dist/
      
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/ProjectFiles/dist/DisplayKeys-IS.exe
          asset_name: "DisplayKeys-IS-Test.exe"
          asset_content_type: application/vnd.microsoft.portable-executable
      
